# Generated by Django 3.0.4 on 2020-03-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotrip_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=75)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('image', models.ImageField(default='default.jpg', upload_to='location_pics')),
            ],
        ),
    ]
