# Generated by Django 3.0 on 2019-12-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotrip_app', '0002_auto_20191216_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='state',
            new_name='state_abbreviation',
        ),
    ]
