# Generated by Django 3.0 on 2019-12-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotrip_app', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='topics',
            field=models.ManyToManyField(to='cotrip_app.Topic'),
        ),
    ]
