# Generated by Django 3.0.5 on 2020-04-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20200403_2012'),
        ('accounts', '0002_profile_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='topics',
            field=models.ManyToManyField(to='community.Topic'),
        ),
    ]
