# Generated by Django 3.0.5 on 2020-04-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_auto_20200402_1934'),
        ('accounts', '0003_auto_20200406_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activities',
            field=models.ManyToManyField(to='trip.Activity'),
        ),
    ]
