# Generated by Django 3.0.5 on 2020-04-07 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_remove_location_people'),
        ('community', '0005_auto_20200406_1920'),
        ('accounts', '0004_profile_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pinterest_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='connections',
            field=models.ManyToManyField(blank=True, null=True, related_name='_profile_connections_+', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, related_name='people', to='community.Event'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to='community.Hashtag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activities',
            field=models.ManyToManyField(blank=True, null=True, related_name='people', to='trip.Activity'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city_of_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='trip.Location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to='community.Topic'),
        ),
        migrations.CreateModel(
            name='ProfileSocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='accounts.Profile')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_social_media', to='accounts.SocialMediaType')),
            ],
        ),
    ]
