# Generated by Django 3.0.5 on 2020-04-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200407_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilesocialmedia',
            old_name='type',
            new_name='social_media_type',
        ),
    ]
