# Generated by Django 3.0.5 on 2020-04-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200408_1809'),
        ('accounts', '0005_auto_20200409_1241'),
    ]

    operations = [
    ]
