# Generated by Django 3.0.6 on 2020-05-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200513_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_subscriber',
        ),
    ]
