# Generated by Django 3.0.6 on 2020-05-14 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_auto_20200514_1638'),
        ('accounts', '0011_remove_customuser_is_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cities_of_residence',
        ),
        migrations.AddField(
            model_name='profile',
            name='city_of_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='trip.Location'),
        ),
    ]
