# Generated by Django 3.0.6 on 2020-05-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200514_1447'),
        ('accounts', '0012_auto_20200514_1814'),
    ]

    operations = [
    ]
