<<<<<<< HEAD
# Generated by Django 3.0.6 on 2020-05-15 19:09
=======
# Generated by Django 3.0.6 on 2020-05-17 19:37
>>>>>>> develop

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200514_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='trips',
        ),
    ]
