# Generated by Django 3.0.6 on 2020-05-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_trips'),
        ('accounts', '0013_merge_20200518_1852'),
    ]

    operations = [
    ]
