# Generated by Django 3.0.7 on 2020-07-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20200518_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='requests',
            field=models.ManyToManyField(blank=True, null=True, related_name='_profile_requests_+', to='accounts.Profile'),
        ),
    ]
