# Generated by Django 3.0.8 on 2020-07-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_media_author'),
        ('accounts', '0015_profile_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='community.Group'),
        ),
    ]
