# Generated by Django 3.0.7 on 2020-07-13 18:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='requests',
        ),
        migrations.AddField(
            model_name='profile',
            name='requests',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=[], size=None),
            preserve_default=False,
        ),
    ]
