# Generated by Django 3.0.7 on 2020-07-13 19:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200713_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='requests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
