# Generated by Django 3.0.8 on 2020-07-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_group_location'),
        ('accounts', '0016_auto_20200706_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='community.Group'),
        ),
    ]
