# Generated by Django 3.0.7 on 2020-07-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200713_1903'),
        ('accounts', '0017_auto_20200709_1346'),
    ]

    operations = [
    ]
