# Generated by Django 3.0.5 on 2020-04-06 19:20

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_activities'),
        ('community', '0005_auto_20200406_1920'),
        ('trip', '0004_auto_20200402_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='date_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='date_start',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 19, 19, 32, 22812, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(default='timezone.now()'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='groups',
            field=models.ManyToManyField(to='community.Group'),
        ),
        migrations.AddField(
            model_name='location',
            name='people',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
