# Generated by Django 3.0.5 on 2020-04-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20200406_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='people',
        ),
    ]
