# Generated by Django 3.0.6 on 2020-05-13 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_remove_location_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(default='NA', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.RemoveField(
            model_name='location',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='attendees',
        ),
        migrations.AddField(
            model_name='location',
            name='code',
            field=models.CharField(default='NA', max_length=2),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='location',
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.ManyToManyField(related_name='activities', to='trip.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='activities',
            field=models.ManyToManyField(related_name='trips', to='trip.Activity'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='locations',
            field=models.ManyToManyField(related_name='trips', to='trip.Location'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(default='NA', max_length=2)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.Country')),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.State'),
        ),
    ]
