# Generated by Django 3.0.6 on 2020-05-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_auto_20200514_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='location',
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trip.Location'),
        ),
    ]
