# Generated by Django 3.0.6 on 2020-05-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0011_auto_20200515_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='attendees',
        ),
    ]
