# Generated by Django 3.0.6 on 2020-05-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0012_trip_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='imageURLs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
