# Generated by Django 3.0.8 on 2020-07-06 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_media_author'),
        ('trip', '0013_trip_imageurls'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location', to='community.Group'),
        ),
    ]
