# Generated by Django 3.0.6 on 2020-05-19 18:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0013_trip_imageurls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='imageURLs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, null=True, size=None),
        ),
    ]
