# Generated by Django 3.0.8 on 2020-07-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0014_location_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='groups',
        ),
    ]
