# Generated by Django 3.0.5 on 2020-04-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='community.Hashtag'),
        ),
        migrations.AlterField(
            model_name='media',
            name='topics',
            field=models.ManyToManyField(blank=True, to='community.Topic'),
        ),
    ]
