# Generated by Django 3.0.5 on 2020-04-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20200403_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='topic',
            name='hashtag',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
