# Generated by Django 3.0.5 on 2020-04-07 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200407_2006'),
        ('community', '0005_auto_20200406_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotripper_media', to='accounts.Profile'),
        ),
    ]
