# Generated by Django 3.0.8 on 2020-07-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_group_location'),
        ('forum', '0005_post_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.Group'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to='forum.Post'),
        ),
    ]
