# Generated by Django 3.0.8 on 2020-07-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20200709_1832'),
        ('forum', '0006_auto_20200707_1710'),
    ]

    operations = [
    ]
